# ===================================================================
# Standard app properties.
# ===================================================================

server:
  port: 7799

  mail:
    host: localhost
    port: 25
    username:
    password:
