# ===================================================================
# Standard app properties.
# ===================================================================

server:
  port: 7789
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
